---
- name: Display running-config 
  hosts: LEAF1 #Replace with address of the device or the file locaiton of the hosts file
  gather_facts: no  #Tells Ansible not to gather facts about the device before running the play 
  connection: network_cli   #Tells Ansible to use the CLI of Arista EOS
  tasks:
    - name: Show running configuration
      eos_command:
        commands:
          - show version    #Displays the software version, uptime, and hardware information
      register: output  #Registers the running-config to output to print in the below section

    - name: Print output
      debug:
        var: output.stdout_lines
