---
- name: Configure ACLs on Arista Switches
  hosts: LEAF1
  gather_facts: no
  connection: network_cli

  tasks:
    - name: Create ACLs
      eos_acls:
        config:
        - afi: ipv4
          acls:
          - name: TestACL
            aces:
            - sequence: 10
              grant: permit
              protocol: icmp
              source:
                any: true
              destination:
                any: true
        state: merged
