---
- name: Configure VLANs on Arista switch
  hosts: LEAF1   #Put the address of the host you want to connect to or the file location of your hosts/inventory file
  gather_facts: no  #Tells Ansible not to gather facts about the device before running the play
  connection: network_cli   #Tells Ansible to use the CLI of Arista EOS
  tasks:
    - name: Create VLANs on Arista switch
      eos_vlans:
        config:
          - name: TestVLAN   #Give your VLAN a fun name here
            state: active    #Set the VLAN state to active or suspened
            vlan_id: 20      #Set the VLAN ID
        state: merged        #Set the state of the VLAN to merged (Default), replaced, overridden, deleted, rendered, gathered, parsed
