---
- name: Configure IPSec VPN on Arista EOS
  hosts: eos    #Replace eos with the name of the host section in the Ansible inventory file
  vars:
    vpn_type: ipsec #Defines the type of VPN to create
    local_address: x.x.x.x  #Local address of the VPN tunnel
    remote_address: x.x.x.x #Remote address of the VPN tunnel
    psk: mysecretpsk    #Your preshare key for the VPN authentication
    interface: Ethernet1
  tasks:
    - name: Generate VPN configuration
      template:
        src: templates/vpnTemplate.j2   #Uses a Jinja2 template from this file location
        dest: /mnt/flash/vpn.conf   #Saves the VPN configuration created from the variables section above and the Jinja2 template to this file destination
    - name: Apply VPN configuration
      eos_command:
        commands:
          - configure replace /mnt/flash/vpn.conf   #Applies the configuration from this file location that was created for the Arista device
