###Note that the brackets are not part of the final file. They are here as a place holder to section the text in them.
- name: Configure OSPF on Arista devices
  hosts: [Name of host section in Ansible inventory file] ###Replace bracket material with an IP address or external hosts file
  vars:
    ospf_network: [network]/[slash number] ###Enter the network and it's slash notation EX: 10.0.0.0/8
    ospf_area: [OSPF area ID] ###Enter the OSPF area ID
  tasks:
  - name: Configure OSPF network ###Replace the name if wanted
    eos_ospf:
      network: "{{ ospf_network }}"
      area: "{{ ospf_area }}"
      state: present
      
###To run this playbook use the below command and make sure to specify the inventory file for Ansible.      
###ansible-playbook -i "inventory file" "playbook file"
###ansible-playbook -i inventory.ini ospf-playbook.yml
