---
- name: Add Arista container switches to an existing Containerlab deployment
  hosts: localhost
  gather_facts: no
  tasks:
  - name: Define new Arista container switches
    set_fact:
      new_arista_switches:
        - name: Chicago_LEAF1
          kind: ceos
          labels:
            graph-icon: switch
            graph-level: 2
          mgmt_ipv4: 172.100.100.121
          ports:
          - '22011:22'
          - 8011:80
          - 44311:443
          startup-config: ~/containerlab/topologies/L2LS/configs/LEAF1.cfg
        - name: Chicago_LEAF2
          kind: ceos
          labels:
            graph-icon: switch
            graph-level: 2
          mgmt_ipv4: 172.100.100.122
          ports:
          - '22012:22'
          - 80012:80
          - 44312:443
          startup-config: ~/containerlab/topologies/L2LS/configs/LEAF2.cfg
        - name: Chicago_LEAF3
          kind: ceos
          labels:
            graph-icon: switch
            graph-level: 2
          mgmt_ipv4: 172.100.100.123
          ports:
          - '22013:22'
          - 8013:80
          - 44313:443
          startup-config: ~/containerlab/topologies/L2LS/configs/LEAF3.cfg
        - name: Chicago_LEAF4
          kind: ceos
          labels:
            graph-icon: switch
            graph-level: 2
          mgmt_ipv4: 172.100.100.124
          ports:
          - '22014:22'
          - 8014:80
          - 44314:443
          startup-config: ~/containerlab/topologies/L2LS/configs/LEAF4.cfg
        - name: Chicago_SPINE1
          kind: ceos
          labels:
            graph-icon: switch
            graph-level: 2
          mgmt_ipv4: 172.100.100.125
          ports:
          - '22015:22'
          - 8015:80
          - 44315:443
          startup-config: ~/containerlab/topologies/L2LS/configs/SPINE1.cfg
        - name: Chicago_SPINE2
          kind: ceos
          labels:
            graph-icon: switch
            graph-level: 2
          mgmt_ipv4: 172.100.100.126
          ports:
          - '22016:22'
          - 8016:80
          - 44316:443
          startup-config: ~/containerlab/topologies/L2LS/configs/SPINE2.cfg
        # Add more new Arista switches if needed

  - name: Read existing containerlab configuration
    slurp:
      src: ~/containerlab/topologies/L2LS/L2LS.yaml
    register: containerlab_config

  - name: Parse containerlab configuration
    set_fact:
      containerlab_config_parsed: "{{ containerlab_config['content'] | b64decode | from_yaml }}"

  - name: Add new Arista container switches to existing configuration
    set_fact:
      updated_containerlab_config: "{{ containerlab_config_parsed | combine({'topology': {'nodes': new_switches}}, recursive=True) }}"
    vars:
      new_switches: "{{ containerlab_config_parsed.topology.nodes | default({}) | combine(dict(new_arista_switches | map(attribute='name') | zip(new_arista_switches | map('combine', {'name': omit})))) }}"

  - name: Write updated containerlab configuration
    copy:
      content: "{{ updated_containerlab_config | to_nice_yaml }}"
      dest: ~/containerlab/topologies/L2LS/updated_containerlab.yml

  - name: Apply updated containerlab configuration
    command:
      cmd: sudo containerlab deploy -t ~/containerlab/topologies/L2LS/updated_containerlab.yml --reconfigure
